### PR TITLE
osx-arm64/aarch64 + rattler-build 

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@mediocretech ready for review!

**Comment by hadim** [comment]
@mediocretech I did merge the recent main commits. Let me know if you have any questions. Otherwise LGTM.

**Comment by hadim** [comment]
Friendly ping @mediocretech if you have time to review this!

**Review by mediocretech — APPROVED** [review]
lgtm 

@hadim you can add yourself as a maintainer

**Comment by hadim** [comment]
done.

**Comment by hadim** [comment]
LGTM

**Pull request merged**
